import React from 'react';
import { useNavigate } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowLeft } from '@fortawesome/free-solid-svg-icons';

const TermsAndConditionsPage: React.FC = () => {
   const navigate = useNavigate();

  const handleBack = () => {
    navigate(-1); // Go back to the previous page
  };
  return (
    <div className="py-12 text-gray-300">
      <div className="max-w-4xl mx-auto space-y-8 glass p-10 rounded-3xl border border-white/10">
                <button
                  onClick={handleBack}
                  className="absolute top-6 left-6 text-gray-400 hover:text-red-500 transition-colors"
                  title="Go Back"
                >
                  <FontAwesomeIcon icon={faArrowLeft} size="lg" />
                </button>
        <h1 className="text-4xl font-bold text-white mb-6">Terms and Conditions</h1>
        <p className="text-sm text-gray-500">Last Updated: January 30, 2026</p>

        <div className="space-y-6">
          <section className="space-y-2">
            <p>
              Please read these Terms and Conditions ("Terms") carefully before using the Backstage Rookie application (the "Service") operated by us.
            </p>
            <p>
              Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-red-500">1. Accounts</h2>
            <p>
              When you create an account with us by authenticating with Google, you must provide us with information that is accurate, complete, and current at all times. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-red-500">2. Use of the Service</h2>
            <p>
              Our Service performs security analysis on public GitHub repositories. You agree not to use the Service for any purpose that is illegal or prohibited by these Terms.
            </p>
            <ul className="list-disc list-inside space-y-2 pl-4">
              <li>You are granted a limited, non-exclusive, non-transferable, revocable license to use the Service.</li>
              <li>You are responsible for the code you submit for analysis and must ensure you have the right to do so.</li>
              <li>The Service analyzes public repositories. Do not submit links to private or sensitive repositories.</li>
              <li>The analysis and reports generated by the Service are for informational purposes only and do not constitute a guarantee of security.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-red-500">3. Intellectual Property</h2>
            <p>
              The Service and its original content, features, and functionality are and will remain the exclusive property of Backstage Rookie and its licensors. The results of any analysis, including generated reports, are your property to use as you see fit.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-red-500">4. Disclaimer of Warranties</h2>
            <p>
              The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement, or course of performance.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-red-500">5. Limitation of Liability</h2>
            <p>
              In no event shall Backstage Rookie, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
          </section>

      <section className="space-y-2">
    <h2 className="text-2xl font-semibold text-red-500">6. Governing Law</h2>
    <p>
      These Terms shall be governed and construed in accordance with the laws of 
      India and the state of Maharashtra, without regard to its conflict of law provisions. 
      Any disputes shall be subject to the exclusive jurisdiction of the courts in Mumbai.
    </p>
</section>

          <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-red-500">7. Changes</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditionsPage;
